[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "evo.ninja"
version = "0.1.0"
description = "A minimal Python package."
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
agbenchmark = { path = "../Auto-GPT/benchmark" }


